steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGISTRY_HOST}/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGISTRY_HOST}/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', '${_SERVICE_NAME}', '--image', '${_REGISTRY_HOST}/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA', '--region', '${_SERVICE_REGION}']
images:
- ${_REGISTRY_HOST}/$PROJECT_ID/${_IMAGE_NAME}:$COMMIT_SHA
